apiVersion: apps/v1
kind: Deployment
metadata:
  name: chat-backend-bauti-fran
spec:
  replicas: 2
  selector:
    matchLabels:
      app: chat-backend-bauti-fran
  template:
    metadata:
      labels:
        app: chat-backend-bauti-fran
    spec:
      containers:
      - name: chat-backend-bauti-fran
        image: bautifrigole/chat-backend:v4.5
        ports:
        - containerPort: 4000
        env:
          - name: REDIS_PASSWORD
            valueFrom:
              secretKeyRef:
                name: redis-cluster
                key: redis-password
          - name: REDIS_IP
            value: "redis-cluster"
---
apiVersion: v1
kind: Service
metadata:
  name: chat-backend-bauti-fran
spec:
  selector:
    app: chat-backend-bauti-fran
  ports:
  - protocol: TCP
    port: 80
    targetPort: 4000
  type: LoadBalancer
