apiVersion: apps/v1
kind: Deployment
metadata:
  name: chat-frontend-bauti-fran
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chat-frontend-bauti-fran
  template:
    metadata:
      labels:
        app: chat-frontend-bauti-fran
    spec:
      containers:
      - name: chat-frontend-bauti-fran
        image: bautifrigole/chat-frontend:latest
        ports:
        - containerPort: 3000
        env:
        - name: NEXT_PUBLIC_BACKEND_URL
          value: "http://10.230.110.12:80" # Esto no se setea en Next porque setea las variables de entorno en tiempo de compilación
        #env:
        #- name: NEXT_PUBLIC_BACKEND_URL
        #  valueFrom:
        #    configMapKeyRef:
        #      name: backend-config
        #      key: BACKEND_URL
---
apiVersion: v1
kind: Service
metadata:
  name: chat-frontend-bauti-fran
spec:
  selector:
    app: chat-frontend-bauti-fran
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3000
  type: LoadBalancer
