apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: first-pool
  namespace: metallb-system
spec:
  addresses:
  - 10.230.110.10-10.230.110.30
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: metallb-bauti-fran
  namespace: metallb-system
